### ISSUE TITLE
own hex code problem

### ISSUE THREAD

**Issue by gadjodilo83** [adafruit/Standalone-Arduino-AVR-ISP-programmer#13]
thank you very much for providing this project. the example can be flashed without problems. However, when I insert my own hex file, this error message always comes up. what can be the reason?

without bootloader
Flashing page 1A00
Commit Page: 0xD00 -> 0xD00
Writing address $ 1A80
Bad hex digit!

with bootloader:
Fuses set & verified
Page size: 128
Chip size: 32768
Writing address $ 0
Too much code

**Comment by ladyada** [comment]
you can try posting in the forums. note this project is not supported for DIY & we dont do tech support in github.
