### ISSUE TITLE
Invalid HEX digit

### ISSUE THREAD

**Issue by vsavic** [adafruit/Standalone-Arduino-AVR-ISP-programmer#5]
When I tried to put my HEX file inside the images.cpp instead of optiboot_atmega328.hex I got an error saying invalid hex digit.

The way how I put the content in images.cpp is that I just open my hex with text editor, and added \n" to the end and " at the beginning of each line.

Sketch was compiled and uploaded successfully but when I press button I got error which I mentioned above.

Any idea why?

Also, what's this: `128,   // size in bytes of flash page`, what `flash page` represent, and should I change that when I want to use my custom hex?

**Comment by ladyada** [comment]
hiya, if you purchased an adafruit kit you can post in our forums. we dont do tech support on github, thanks! :)

**Comment by vsavic** [comment]
Ok I posted a topic there https://forums.adafruit.com/viewtopic.php?f=19&t=132573
